// Copyright 2023 QMK Contributors <@qmk>
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define RGB_MATRIX_DEFAULT_HUE 157
#define RGB_MATRIX_DEFAULT_SAT 127

#undef ENABLE_RGB_MATRIX_PIXEL_FLOW
#undef ENABLE_RGB_MATRIX_PIXEL_RAIN
#undef ENABLE_RGB_MATRIX_RAINBOW_BEACON
#undef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#undef ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS

#define MODIFIER_INDICATORS 10
#define LAYER_INDICATORS 9
#define CAPS_LOCK_INDICATORS 4, 5
