// Copyright 2023 QMK Contributors <@qmk>
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

//#define STARTUP_SONG SONG(WORKMAN_SOUND)
//#define STARTUP_SONG SONG(QWERTY_SOUND)
//#define STARTUP_SONG SONG(DVORAK_SOUND)
//#define STARTUP_SONG SONG(COLEMAK_SOUND)
//#define STARTUP_SONG SONG(PLOVER_SOUND)
//#define STARTUP_SONG SONG(PLOVER_GOODBYE_SOUND)

/*
#undef TEMPO_DEFAULT
#define TEMPO_DEFAULT 60
#define AUDIO_CLICKY_DELAY_DURATION 2
*/

#define ENCODER_DIRECTION_FLIP

#define RGB_MATRIX_DEFAULT_HUE 130
#define RGB_MATRIX_DEFAULT_VAL 64
#define RGB_MATRIX_DEFAULT_SAT 240

#define LAYER_INDICATORS 2
#define MODIFIER_INDICATORS 1
#define CAPS_LOCK_INDICATORS 0
